version: '3'
services:
  app:
    build: .
    ports:
      - "8808:8808"
    environment:
      - PORT=8808
      - LISTMONK_URL=http://listmonk:9000
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=password
    depends_on:
      - listmonk

  listmonk:
    image: listmonk/listmonk:latest
    ports:
      - "9000:9000"
    environment:
      - APP_DB_HOST=db
      - APP_DB_USER=listmonk
      - APP_DB_PASSWORD=listmonk
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=listmonk
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_DB=listmonk
    volumes:
      - listmonk-data:/var/lib/postgresql/data

volumes:
  listmonk-data: